print(f'A classe de 1 = {type(1)}')
print(f'A classe de True = {type(True)}')
print(f'A classe do resultado de 5 / 2 = {type(5 / 2)}')
print(f'A classe de 2.5 = {type(2.5)}')
print(f'A classe de False = {type(False)}')
print(f'A classe do resultado de 5 + 3 = {type(5 + 3)}')
